/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

//Variable naammes;
//Grading.tab{
// stdID;
//stdName;
//crsOop;
//crsDld;
//crsPns;
//crsOb;
//crsIr;
//crsComm;
//obtMarks;
//percentage;
//grade;
//logoutbtn;
//searchBtn;
//calculateBtn;
//submitBtn;
//]

//Upload Assignment.tab{
// crsOop2;
//crsDld2;
//crsIr2;
//crsOb2;
//crsPns2;
//crsComm2;
//uploadAssignment;
//uploadBtn;
//}

//ViewDetail.tab{
//teacherName;
//teacherId;
//teacherDepart;
//teacherCourseTable;}


import java.awt.*;

public class TeacherPanel extends javax.swing.JFrame {

    /**
     * Creates new form teacherPanel
     */
    Teacher currentUser = MyFiler.getTeacher();
    Teacher teachers[] = new Teacher[50];
    public TeacherPanel() {
        initComponents();
        teacherName.setText(currentUser.name);
        teacherId.setText(currentUser.id);
        teacherDepart.setText(currentUser.department);
        crsOop.setEnabled(false);
        crsDld.setEnabled(false);
        crsPns.setEnabled(false);
        crsOb.setEnabled(false);
        crsIr.setEnabled(false);
        crsComm.setEnabled(false);
        crsOop2.setEnabled(false);
        crsDld2.setEnabled(false);
        crsPns2.setEnabled(false);
        crsOb2.setEnabled(false);
        crsIr2.setEnabled(false);
        crsComm2.setEnabled(false);

        accountHoldersName.setText(currentUser.name);
        int c=0;
        try{
            for(int i=0; i<6; i++){
                if(currentUser.courses[i] == null)
                    continue;

                teacherCourseTable.setValueAt(currentUser.courses[i].title,i,0);
                for(int j=0; j<6; j++){
                    if(currentUser.courses[j].title.compareToIgnoreCase("OOP") == 0){
                        crsOop.setEnabled(true);
                        crsOop2.setEnabled(true);
                        teacherCourseTable.setValueAt(currentUser.courses[j].title,c,0);
                        c++;
                    }
                    if(currentUser.courses[j].title.compareToIgnoreCase("DLD") == 0){
                        crsDld.setEnabled(true);
                        crsDld2.setEnabled(true);
                        teacherCourseTable.setValueAt(currentUser.courses[j].title,c,0);
                        c++;
                    }
                    if(currentUser.courses[j].title.compareToIgnoreCase("COM") == 0){
                        crsComm.setEnabled(true);
                        crsComm2.setEnabled(true);
                        teacherCourseTable.setValueAt(currentUser.courses[j].title,c,0);
                        c++;
                    }
                    if(currentUser.courses[j].title.compareToIgnoreCase("STATS") == 0){
                        crsPns.setEnabled(true);
                        crsPns2.setEnabled(true);
                        teacherCourseTable.setValueAt(currentUser.courses[j].title,c,0);
                        c++;
                    }
                    if(currentUser.courses[j].title.compareToIgnoreCase("OB") == 0){
                        crsOb.setEnabled(true);
                        crsOb2.setEnabled(true);
                        teacherCourseTable.setValueAt(currentUser.courses[j].title,c,0);
                        c++;
                    }
                    if(currentUser.courses[j].title.compareToIgnoreCase("IR") == 0){
                        crsIr.setEnabled(true);
                        crsIr2.setEnabled(true);
                        teacherCourseTable.setValueAt(currentUser.courses[j].title,c,0);
                        c++;
                    }
                }
            }
        } catch (Exception e){

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        accountHoldersName = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        stdId = new javax.swing.JTextField();
        stdName = new javax.swing.JTextField();
        crsOb = new javax.swing.JRadioButton();
        crsIr = new javax.swing.JRadioButton();
        crsDld = new javax.swing.JRadioButton();
        crsOop = new javax.swing.JRadioButton();
        crsComm = new javax.swing.JRadioButton();
        crsPns = new javax.swing.JRadioButton();
        searchBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        obtMarks = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        grade = new javax.swing.JTextField();
        calculateBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        warning1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        crsDld2 = new javax.swing.JRadioButton();
        crsComm2 = new javax.swing.JRadioButton();
        crsIr2 = new javax.swing.JRadioButton();
        crsOb2 = new javax.swing.JRadioButton();
        crsPns2 = new javax.swing.JRadioButton();
        crsOop2 = new javax.swing.JRadioButton();
        uploadAssignment = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        uploadBtn = new javax.swing.JButton();
        warning2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        teacherCourseTable = new javax.swing.JTable();
        teacherId = new javax.swing.JTextField();
        teacherName = new javax.swing.JTextField();
        teacherDepart = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        accountHoldersName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        accountHoldersName.setText("accountHoldersName");

        logoutBtn.setText("Logout");
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });

        jLabel4.setText("Student ID :");

        jLabel5.setText("Student Name : ");

        stdName.setEditable(false);

        buttonGroup1.add(crsOb);
        crsOb.setText("OB");

        buttonGroup1.add(crsIr);
        crsIr.setText("IR");

        buttonGroup1.add(crsDld);
        crsDld.setText("DLD");

        buttonGroup1.add(crsOop);
        crsOop.setText("OOP");

        buttonGroup1.add(crsComm);
        crsComm.setText("COM");

        buttonGroup1.add(crsPns);
        crsPns.setText("P&S");

        searchBtn.setText("SEARCH");
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("COURSES");

        jLabel7.setText("ENTER MARKS OBTAINED ");

        obtMarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obtMarksActionPerformed(evt);
            }
        });

        jLabel9.setText("GRADE :");

        grade.setEditable(false);

        calculateBtn.setText("CALCULATE");
        calculateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calculateBtnMouseClicked(evt);
            }
        });

        submitBtn.setText("SUBMIT");
        submitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitBtnMouseClicked(evt);
            }
        });

        warning1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        warning1.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(308, 308, 308)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(submitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(calculateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel7)
                                                                        .addComponent(jLabel9))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(grade, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(obtMarks, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addContainerGap(183, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(crsOop)
                                                                        .addComponent(crsPns)
                                                                        .addComponent(crsOb))
                                                                .addGap(33, 33, 33)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(crsIr)
                                                                        .addComponent(crsComm)
                                                                        .addComponent(crsDld))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(warning1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel4)
                                                                                        .addComponent(jLabel5))
                                                                                .addGap(33, 33, 33)
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                        .addComponent(stdId, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                                                                        .addComponent(stdName))
                                                                                .addGap(31, 31, 31)
                                                                                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(jLabel6))
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addGap(16, 16, 16))))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(stdId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(searchBtn)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(stdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(warning1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(crsOop)
                                                        .addComponent(crsDld))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(crsPns)
                                                        .addComponent(crsComm))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(crsOb)
                                                        .addComponent(crsIr))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(obtMarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(calculateBtn))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel9)
                                        .addComponent(grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(submitBtn))
                                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Grading", jPanel1);

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel10.setText("SELECT COURSES");

        buttonGroup2.add(crsDld2);
        crsDld2.setText("DLD");
        crsDld2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crsDld2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(crsComm2);
        crsComm2.setText("COM");

        buttonGroup2.add(crsIr2);
        crsIr2.setText("IR");

        buttonGroup2.add(crsOb2);
        crsOb2.setText("OB");

        buttonGroup2.add(crsPns2);
        crsPns2.setText("P&S");

        buttonGroup2.add(crsOop2);
        crsOop2.setText("OOP");

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel11.setText("ASSIGNMENT :");

        uploadBtn.setText("UPLOAD");
        uploadBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uploadBtnMouseClicked(evt);
            }
        });

        warning2.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(jLabel11)
                                                                .addGap(26, 26, 26)
                                                                .addComponent(uploadAssignment, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jLabel10)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(crsOb2)
                                                                        .addComponent(crsPns2)
                                                                        .addComponent(crsOop2))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(crsIr2)
                                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(crsComm2)
                                                                                .addComponent(crsDld2, javax.swing.GroupLayout.Alignment.LEADING))))))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(203, 203, 203)
                                                .addComponent(uploadBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(154, 154, 154)
                                                .addComponent(warning2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(227, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(crsDld2)
                                        .addComponent(crsOop2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(crsComm2)
                                        .addComponent(crsPns2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(crsIr2)
                                        .addComponent(crsOb2))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(uploadAssignment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(warning2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(uploadBtn)
                                .addContainerGap(100, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Upload Assignment", jPanel2);

        jLabel12.setText("Teacher ID :");

        jLabel13.setText("Teacher Name :");

        jLabel14.setText("Department :");

        teacherCourseTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null},
                        {null},
                        {null},
                        {null},
                        {null},
                        {null}
                },
                new String [] {
                        "COURSES"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(teacherCourseTable);
        if (teacherCourseTable.getColumnModel().getColumnCount() > 0) {
            teacherCourseTable.getColumnModel().getColumn(0).setResizable(false);
        }

        teacherId.setEditable(false);

        teacherName.setEditable(false);

        teacherDepart.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel12)
                                                        .addComponent(jLabel13)
                                                        .addComponent(jLabel14))
                                                .addGap(29, 29, 29)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(teacherDepart)
                                                        .addComponent(teacherName)
                                                        .addComponent(teacherId))))
                                .addGap(316, 316, 316))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(teacherId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(teacherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(teacherDepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(90, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View Details", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(accountHoldersName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logoutBtn))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(logoutBtn)
                                        .addComponent(accountHoldersName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTabbedPane1)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void obtMarksActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void crsDld2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        Main.main(new String['a']);
        dispose();
    }

    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        System.out.println("DID IT");
        stdId.getText();
        stdName.setForeground(Color.black);
        Student students[] = new Student[50];
        boolean found = false;
        MyFiler.readFile(students);
        System.out.println("howwww");
        try{
            for(int i=0; i<50; i++){
                if(stdId.getText().compareTo(students[i].id) == 0){
                    found = true;
                    stdName.setText(students[i].name);
                    break;
                }
            }

        } catch (Exception e){
            System.out.println(e);

        }

        if(!found){
            stdName.setForeground(Color.red);
            stdName.setText("User not Found");
        }
    }

    private boolean calculateBtnMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        // TODO add your handling code here:
        warning1.setForeground(Color.red);
        warning1.setText("");
        Student students[] = new Student[50];
        MyFiler.readFile(students);
        String course;
        if(Integer.parseInt(obtMarks.getText()) > 100 || Integer.parseInt(obtMarks.getText()) < 0){
            warning1.setText("Invalid input");
            return false;
        }
        if(crsOop.isSelected()){
            course = "OOP";
        } else if(crsDld.isSelected()) {
            course = "DLD";
        } else if (crsIr.isSelected()){
            course = "IR";
        } else if (crsOb.isSelected()){
            course = "OB";
        } else if (crsPns.isSelected()){
            course = "STATS";
        } else if (crsComm.isSelected()){
            course = "COM";
        } else{
            warning1.setText("Please Fill all Fields");
            return false;
        }
        if(obtMarks.getText().compareTo("") == 0){
            warning1.setText("Please Fill all Fields");
            return false;
        }

        try{
            grade.setText(Course.seeGrade(Integer.parseInt(obtMarks.getText())));
        } catch (Exception e){
            System.out.println(e);
        }
        return true;
    }

    private boolean submitBtnMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        warning1.setForeground(Color.red);
        warning1.setText("");
        Student students[] = new Student[50];
        MyFiler.readFile(students);
        String course;
        boolean found = true;


        if(crsOop.isSelected()){
            course = "OOP";
        } else if(crsDld.isSelected()) {
            course = "DLD";
        } else if (crsIr.isSelected()){
            course = "IR";
        } else if (crsOb.isSelected()){
            course = "OB";
        } else if (crsPns.isSelected()){
            course = "STATS";
        } else if (crsComm.isSelected()){
            course = "COM";
        } else{
            warning1.setText("Please All Fields");
            return false;
        }
        if(stdId.getText().compareTo("") == 0 && obtMarks.getText().compareTo("") == 0 ){
            warning1.setText("Please All Fields");
            return false;
        }

        try{
            for(int i=0; i<50; i++){
                if(students[i].id.compareToIgnoreCase(stdId.getText()) == 0){
                    found = false;
                    for(int j=0; j<6; j++){
                        if(students[i].courses[j].title.compareToIgnoreCase(course) == 0){
                            if(!students[i].courses[j].setGrade(Integer.parseInt(obtMarks.getText()))){
                                warning1.setText("Unable to set");
                                return false;
                            }

                            MyFiler.changeObject(students[i],students);
                            warning1.setForeground(Color.green);
                            warning1.setText("Updated");
                            buttonGroup1.clearSelection();

                        }
                    }
                }
            }
        } catch (Exception e){
            System.out.println(e);
        }


        if (found){
            warning1.setText("Not Found");
            return false;
        }

        return true;
    }

    private boolean uploadBtnMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        warning2.setForeground(Color.red);
        warning2.setText("");
        String course;
        Student students[] = new Student[50];
        MyFiler.readFile(students);
        if(crsOop2.isSelected()){
            course = "OOP";
        } else if(crsDld2.isSelected()) {
            course = "DLD";
        } else if (crsIr2.isSelected()){
            course = "IR";
        } else if (crsOb2.isSelected()){
            course = "OB";
        } else if (crsPns2.isSelected()){
            course = "STATS";
        } else if (crsComm2.isSelected()){
            course = "COM";
        } else{
            warning2.setText("Please Fill all Fields");
            return false;
        }
        if(uploadAssignment.getText().compareTo("") == 0){
            warning2.setText("Please Fill all Fields");
            return false;
        }

        try{
            for(int i=0; i<50; i++){
                if(students[i] == null){
                    break;
                }
                for(int j=0; j<6; j++){
                    if(students[i].courses[j] == null) {
                        uploadAssignment.setText("");
                        break;
                    }
                    if(students[i].courses[j].title.compareToIgnoreCase(course) == 0){
                        students[i].courses[j].setAssignment(uploadAssignment.getText());
                        warning2.setForeground(Color.green);
                        System.out.println( students[i].name + "    " + students[i].courses[j].title);
                        MyFiler.changeObject(students[i],students);
                        buttonGroup2.clearSelection();
                        warning2.setText("Updated");
                        break;
                    }

                }
            }
        } catch (Exception e){
            System.out.println("kiuuuuun "+e);
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherPanel().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel accountHoldersName;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton calculateBtn;
    private javax.swing.JRadioButton crsComm;
    private javax.swing.JRadioButton crsComm2;
    private javax.swing.JRadioButton crsDld;
    private javax.swing.JRadioButton crsDld2;
    private javax.swing.JRadioButton crsIr;
    private javax.swing.JRadioButton crsIr2;
    private javax.swing.JRadioButton crsOb;
    private javax.swing.JRadioButton crsOb2;
    private javax.swing.JRadioButton crsOop;
    private javax.swing.JRadioButton crsOop2;
    private javax.swing.JRadioButton crsPns;
    private javax.swing.JRadioButton crsPns2;
    private javax.swing.JTextField grade;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTextField obtMarks;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField stdId;
    private javax.swing.JTextField stdName;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTable teacherCourseTable;
    private javax.swing.JTextField teacherDepart;
    private javax.swing.JTextField teacherId;
    private javax.swing.JTextField teacherName;
    private javax.swing.JTextField uploadAssignment;
    private javax.swing.JButton uploadBtn;
    private javax.swing.JLabel warning1;
    private javax.swing.JLabel warning2;
    // End of variables declaration
}
